
title: Personal page of Kamalaker Dadi
my_github: https://github.com/KamalakerDadi
my_scholar: https://scholar.google.com/citations?user=0u695CEAAAAJ
github_username: KamalakerDadi
theme: minima


plugins:
  - jekyll-feed
  - jekyll-seo-tag

